--
-- PostgreSQL database dump
--

\restrict iXI7uvAvbgwufm6TZthtkIi3biAuhXAhZOLxZGGlLiEAnsCkdSyhJ3I5abRIsB9

-- Dumped from database version 15.17 (Debian 15.17-1.pgdg13+1)
-- Dumped by pg_dump version 15.17 (Debian 15.17-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: root
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO root;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: root
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: click_event; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.click_event (
    id bigint NOT NULL,
    browser character varying(255),
    city character varying(255),
    click_date timestamp(6) without time zone NOT NULL,
    country character varying(255),
    device_type character varying(255),
    ip_hash character varying(255),
    language character varying(255),
    os character varying(255),
    referrer character varying(255),
    url_mapping_id bigint NOT NULL
);


ALTER TABLE public.click_event OWNER TO root;

--
-- Name: click_event_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.click_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.click_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    token_hash character varying(64) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_token OWNER TO root;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: url_edit_history; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.url_edit_history (
    id bigint NOT NULL,
    changed_at timestamp(6) without time zone,
    old_url character varying(255),
    url_mapping_id bigint NOT NULL
);


ALTER TABLE public.url_edit_history OWNER TO root;

--
-- Name: url_edit_history_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.url_edit_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.url_edit_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: url_mapping; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.url_mapping (
    id bigint NOT NULL,
    click_count integer NOT NULL,
    created_date timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone,
    last_clicked_at timestamp(6) without time zone,
    max_clicks integer,
    original_url character varying(2048) NOT NULL,
    short_url character varying(50) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(150),
    version bigint,
    user_id bigint NOT NULL,
    CONSTRAINT url_mapping_status_check CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('EXPIRED'::character varying)::text, ('CLICK_LIMIT_REACHED'::character varying)::text, ('DISABLED'::character varying)::text])))
);


ALTER TABLE public.url_mapping OWNER TO root;

--
-- Name: url_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.url_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.url_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: url_unique_visitor; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.url_unique_visitor (
    id bigint NOT NULL,
    first_seen_at timestamp(6) without time zone NOT NULL,
    ip_hash character varying(64) NOT NULL,
    url_mapping_id bigint NOT NULL
);


ALTER TABLE public.url_unique_visitor OWNER TO root;

--
-- Name: url_unique_visitor_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.url_unique_visitor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.url_unique_visitor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url character varying(500),
    bio character varying(300),
    bio_page_views bigint NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    username character varying(30) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY (ARRAY[('ROLE_USER'::character varying)::text, ('ROLE_PREMIUM'::character varying)::text, ('ROLE_ADMIN'::character varying)::text])))
);


ALTER TABLE public.users OWNER TO root;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: click_event click_event_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.click_event
    ADD CONSTRAINT click_event_pkey PRIMARY KEY (id);


--
-- Name: users idx_email; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_email UNIQUE (email);


--
-- Name: users idx_username; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_username UNIQUE (username);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: url_unique_visitor uk_unique_visitor_url_ip; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_unique_visitor
    ADD CONSTRAINT uk_unique_visitor_url_ip UNIQUE (url_mapping_id, ip_hash);


--
-- Name: refresh_token ukkdj16cltjxdksuyiosdhliveg; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukkdj16cltjxdksuyiosdhliveg UNIQUE (token_hash);


--
-- Name: url_mapping ukluxssvi0fl5akdeuachjtgvgg; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_mapping
    ADD CONSTRAINT ukluxssvi0fl5akdeuachjtgvgg UNIQUE (short_url);


--
-- Name: url_edit_history url_edit_history_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_edit_history
    ADD CONSTRAINT url_edit_history_pkey PRIMARY KEY (id);


--
-- Name: url_mapping url_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_mapping
    ADD CONSTRAINT url_mapping_pkey PRIMARY KEY (id);


--
-- Name: url_unique_visitor url_unique_visitor_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_unique_visitor
    ADD CONSTRAINT url_unique_visitor_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_click_date; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_click_date ON public.click_event USING btree (click_date);


--
-- Name: idx_click_ip_hash; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_click_ip_hash ON public.click_event USING btree (url_mapping_id, ip_hash);


--
-- Name: idx_click_url_mapping; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_click_url_mapping ON public.click_event USING btree (url_mapping_id);


--
-- Name: idx_edit_history_date; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_edit_history_date ON public.url_edit_history USING btree (changed_at);


--
-- Name: idx_edit_history_url; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_edit_history_url ON public.url_edit_history USING btree (url_mapping_id);


--
-- Name: idx_expires_at; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_expires_at ON public.url_mapping USING btree (expires_at);


--
-- Name: idx_refresh_token_expiry; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_refresh_token_expiry ON public.refresh_token USING btree (expires_at);


--
-- Name: idx_refresh_token_hash; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_refresh_token_hash ON public.refresh_token USING btree (token_hash);


--
-- Name: idx_refresh_token_user; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_refresh_token_user ON public.refresh_token USING btree (user_id);


--
-- Name: idx_status; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_status ON public.url_mapping USING btree (status);


--
-- Name: idx_unique_visitor_ip; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_unique_visitor_ip ON public.url_unique_visitor USING btree (ip_hash);


--
-- Name: idx_unique_visitor_url; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_unique_visitor_url ON public.url_unique_visitor USING btree (url_mapping_id);


--
-- Name: idx_user; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX idx_user ON public.url_mapping USING btree (user_id);


--
-- Name: click_event fk569i4rsslbjh08ffdc4iumly2; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.click_event
    ADD CONSTRAINT fk569i4rsslbjh08ffdc4iumly2 FOREIGN KEY (url_mapping_id) REFERENCES public.url_mapping(id);


--
-- Name: refresh_token fkjtx87i0jvq2svedphegvdwcuy; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkjtx87i0jvq2svedphegvdwcuy FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: url_unique_visitor fknr3lk573ttva1k8tmkkbv8csg; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_unique_visitor
    ADD CONSTRAINT fknr3lk573ttva1k8tmkkbv8csg FOREIGN KEY (url_mapping_id) REFERENCES public.url_mapping(id);


--
-- Name: url_mapping fkpd4vqdk4o6lis35i2b1vo96v0; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_mapping
    ADD CONSTRAINT fkpd4vqdk4o6lis35i2b1vo96v0 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: url_edit_history fktrj7g8mkjld5987455fj0d2ay; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.url_edit_history
    ADD CONSTRAINT fktrj7g8mkjld5987455fj0d2ay FOREIGN KEY (url_mapping_id) REFERENCES public.url_mapping(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: root
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


--
-- PostgreSQL database dump complete
--

\unrestrict iXI7uvAvbgwufm6TZthtkIi3biAuhXAhZOLxZGGlLiEAnsCkdSyhJ3I5abRIsB9

